### ISSUE TITLE
Helper methods in PhWorld ontologies may not work

### ISSUE THREAD

**Issue by Alfiva** [universAAL/ontology#230]
_Originally Opened: @Alfiva (2012-10-11 11:16:44_)
_Originally Closed: 2013-07-01 20:34:14_

Some helper methods of PhWorld ontology classes involving multiple-value properties do not work correctly depending on the amount of values.

This for instance happens in the method getAdjacentLocations() of class Location, which attempts to return all adjacent locations as a list, but when there is only one single value in that property the conversion fails.

This has happened to me in other similar methods in PhWorld as well.

Of course this is not critical because one can use getProperty directly and handle the multi-values himself, but it´s annoying.

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by Alfiva** [comment]
_Original author: @cstockloew (2012-10-12 15:02:45)_

I found some bugs and fixed them (for now, only in Location class) but I cannot reproduce your error:

	Location l = new Location();

	for (int j = 0; j &lt; 5; j++) {
	    Location[] a = l.getAdjacentLocations();

	    System.out.println(&quot;--- size: &quot; + a.length);

	    for (int i = 0; i &lt; a.length; i++)
		System.out.println(&quot;---- &quot; + a[i].toString());

	    l.addAdjacentLocation(new Location(&quot;test&quot; + j));
	}

This code adds some adjacent location and gets and prints the list of adjacent locations. 
Output:
--- size: 0
--- size: 1
---- test0
--- size: 2
---- test0
---- test1
--- size: 3
---- test0
---- test1
---- test2
--- size: 4
---- test0
---- test1
---- test2
---- test3

So, everything works as expected. The fix I made was for 0 adjacent locations (which now returns an array with 0 elements instead of null), but for 1 adjacent location it works.

Did the error occur with 0 or with 1 element? What was the exact error message?

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2012-10-15 09:21:34)_

After having added an adjacent location, when getting an array of Locations from the method getAdjacentLocations I get the following error:

Exception in thread &quot;AWT-EventQueue-0&quot; java.lang.ClassCastException: org.universAAL.ontology.location.Location cannot be cast to java.util.List
	at org.universAAL.ontology.location.Location.getMultipleValueLocationProperty(Location.java:137)
	at org.universAAL.ontology.location.Location.getAdjacentLocations(Location.java:175)

I must say that the way I added the adjacent location was with a SPARQL UPDATE query, directly in RDF, into the CHE, and consequently there is a serialization and parsing in the middle. Probably it´s because of that.

**Comment by Alfiva** [comment]
_Original author: @bennysa (2013-05-07 10:34:54)_

Hi Alvaro,

I have commited a proposed fix  (to the issue. Can you tell me if that solves the problem?

This is my first commit, by the way ;)

best,
benny

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2013-05-07 11:27:55)_

I do not have much time right now to recover the scenario and try again. However, by inspecting the code, I´d say the risk is still there. While the fix may have prevented some bugs, it appears the previous risk is still there in getMultipleValueLocationProperty, in List conn = (List) props.get(propURI); because it is assuming that it is always a list in that property, but with serialization in the middle, there is the possibility that the content of that property is actually a Location object (for when there is only one) instead of a List. Hence the cast exception. I guess that would be avoided by checking the instanceof the props.get result.

**Comment by Alfiva** [comment]
_Original author: @bennysa (2013-05-15 13:36:06)_

Hi,

I reverted the first fix and introduced another change which should catch all relevant scenarios.

kindly check if your scenario works as expected.

best,
benny

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2013-05-16 18:01:04)_

Sorry but again I couldn´t test the scenario and I only looked at the code. It would appear the last fix could work, but it seems to be a &quot;long shortcut&quot; if you know what I mean.
This links to an ancient support tracker item (112) I opened which has never been answered. This fix for multiple-value properties IMHO should be handled at some point in the root of ontologies, in the superclass (say, ManagedIndividual setProperty). If ManagedIndividual makes no assumption on whether to store a single object or a list, then this should be discerned when getting the property back.
What I´m trying to say is that what you did in the fix should be done in MangedIndividual, and if it is not, then you have to check the result of getting the property to cast to either list or object.
I think Carsten will have to make the call here. I vote for second solution, so this does not interfere with root handling of onts as it is now (changing it could affect serialization).

**Comment by Alfiva** [comment]
_Original author: @cstockloew (2013-07-01 20:34:14)_

answered in Wiki:
http://forge.universaal.org/wiki/middleware:Data_Representation_Building_Block#Resources_and_properties
http://forge.universaal.org/wiki/middleware:Data_Representation_Building_Block#OWL_classes

**Comment by Alfiva** [comment]
issue cloed on 2013-07-01 20:34:14
